var windenfahrer_official = null;
var startleiter_official = null;
var flugtag_formatted = null;
var flugtag_unformatted = null;
var isFlugtag = false;
var flugtag_deadline = null;
var intervalId = null; // intervall for counter
var min_pilot_amount_reached = false;
var total_pilot_count_all = new Array(SiteCount).fill(0);
var total_pilot_count_hdgf = new Array(SiteCount).fill(0);
var Active_Pilot_Choices = new Array(SiteCount).fill(null);
var enteredDienste = [];
var dashboardData = [];
var dashboardDataHistory = [];
const thisYear = new Date().getFullYear();
var Saison = 1;
var saisonJahr = thisYear;
var saisonStartDate = calcSeasonStart({ earliestCalenderDate: true });
var saisonEndDate = calcSeasonEnd({ latestCalenderDate: true });
var Flugtage = [];
var FlugtageRaw = [];

var Flugbetrieb = new Array(SiteCount).fill(false);
var FlugbetriebAbgesagt = false;
