<?php

return [
    'basePath' => 'flugplanung',

    'clubId' => 198,

    'sites' => ['Neustadt-Glewe', 'Hörpel', 'Altenmedingen'],

    'newsletterSecret' => 'define_a_secure_random_string_here',

    'smtpDsn' => 'smtp://user:password@smtp.example.com:587',

    'newsletterFrom' => 'Newsletter <newsletter@yourdomain.de>',

    'db' => [
        'servername' => $_SERVER['DATABASE_HOST'] ?? 'localhost',
        'username' => $_SERVER['DATABASE_USER'] ?? '',
        'password' => $_SERVER['DATABASE_PASSWORD'] ?? '',
        'dbname' => $_SERVER['DATABASE_NAME'] ?? 'flugplanung',
        'port' => $_SERVER['DATABASE_PORT'] ?? 3306,
    ],

    'email' => [
        'dsn' => $_SERVER['EMAIL_DSN'] ?? 'smtp://user:password@smtp.example.com:587',
        'from' => $_SERVER['EMAIL_FROM'] ?? 'no-reply@nothing.invalid'
    ],

    'clubs' => [
        0 => ['name' => 'Kein Verein', 'shortName' => ''],
        1 => ['name' => '08/15 Parajumpers e.V.', 'shortName' => ''],
        2 => ['name' => '1. Bamberger Gleitschirm Club e.V.', 'shortName' => ''],
        3 => ['name' => '1. Cottbuser Drachen- und Gleitschirmfliegerclub e.V.', 'shortName' => ''],
        4 => ['name' => '1. Drachen-und Gleitschirmclub Jura Altmuehltal e.V.', 'shortName' => ''],
        5 => ['name' => '1. Drachenfliegerclub Sachsen e.V.', 'shortName' => ''],
        6 => ['name' => '1. Drachenflugclub Wasserkuppe e.V.', 'shortName' => ''],
        7 => ['name' => '1. Gleitschirmverein Bayerwald e.V.', 'shortName' => ''],
        8 => ['name' => '1. Harsberger Gleitschirm- u. Drachenclub Lauterbach e.V.', 'shortName' => ''],
        9 => ['name' => '1. Oberpfaelzer Drachenfliegerclub Riedenburg e.V.', 'shortName' => ''],
        10 => ['name' => '1. Odenwaelder Drachen- u. Gleitschirmflieger-Club e.V.', 'shortName' => ''],
        11 => ['name' => '1. Para-Ski-Club Saar e.V.', 'shortName' => ''],
        12 => ['name' => '1. Parafly-Club Schwaben e.V.', 'shortName' => ''],
        13 => ['name' => '1. Pfaelzer Drachen-u. Gleitschirmfliegerclub e.V.', 'shortName' => ''],
        14 => ['name' => 'AERO Club Altena-Hegenscheid e.V.', 'shortName' => ''],
        15 => ['name' => 'Air Team Neuss e.V.', 'shortName' => ''],
        16 => ['name' => 'Airbus-Sportgemeinschaft Ottobrunn e.V.', 'shortName' => ''],
        17 => ['name' => 'Airwalker e.V.', 'shortName' => ''],
        18 => ['name' => 'Albatros-Gleitsegelclub Aschaffenburg e.V.', 'shortName' => ''],
        19 => ['name' => 'Alpspitzflieger e.V.', 'shortName' => ''],
        20 => ['name' => 'Ammergauer Drachen- und Gleitschirmflieger e.V.', 'shortName' => ''],
        21 => ['name' => 'Asslarer Gleitschirmflieger e.V.', 'shortName' => ''],
        22 => ['name' => 'Aufwind-Brettachtal e.V.', 'shortName' => ''],
        23 => ['name' => 'Aufwindfreunde e.V.', 'shortName' => ''],
        24 => ['name' => 'Augsburger Drachenflieger e.V.', 'shortName' => ''],
        25 => ['name' => 'Baarflieger Fuerstenberg-Geisingen e.V.', 'shortName' => ''],
        26 => ['name' => 'Berchtesgadener Drachenflieger e.V.', 'shortName' => ''],
        27 => ['name' => 'Berchtesgadener Gleitschirmflieger e.V.', 'shortName' => ''],
        28 => ['name' => 'Bergdohlen Brannenburg e.V.', 'shortName' => ''],
        29 => ['name' => 'Bergstraessler Drachenflieger e.V.', 'shortName' => ''],
        30 => ['name' => 'Bodenlos e.V.', 'shortName' => ''],
        31 => ['name' => 'Club fuer Drachenflugsport e.V. Hardheim', 'shortName' => ''],
        32 => ['name' => 'Condor e.V. zur Foerderung des Gleitschirmfliegens', 'shortName' => ''],
        33 => ['name' => 'd\'Allgaeuer Drachenflieger e.V.', 'shortName' => ''],
        34 => ['name' => 'D\'Schwoba Schwaebische Drachenflieger Erbach e.V.', 'shortName' => ''],
        35 => ['name' => 'd\'Waelder Drachenflieger e.V.', 'shortName' => ''],
        36 => ['name' => 'Deisterflieger e.V.', 'shortName' => ''],
        37 => ['name' => 'Delta Club Bavaria Ruhpolding e.V.', 'shortName' => ''],
        38 => ['name' => 'Delta Club Condor e.V. (Wehr)', 'shortName' => ''],
        39 => ['name' => 'Delta Flug Todtnau e.V.', 'shortName' => ''],
        40 => ['name' => 'Delta-Club Ith e.V.', 'shortName' => ''],
        41 => ['name' => 'Delta-Club Mosbach e.V.', 'shortName' => ''],
        42 => ['name' => 'Delta-Club Rheinland e.V.', 'shortName' => ''],
        43 => ['name' => 'Delta-Club Wiehengebirge e.V.', 'shortName' => ''],
        44 => ['name' => 'Deltaclub Teutoburger Wald e.V.', 'shortName' => ''],
        45 => ['name' => 'Der Flieger Club Achental e.V.', 'shortName' => ''],
        46 => ['name' => 'DFC u. GSC im Luftsportverein Laucha-Dorndorf e.V.', 'shortName' => ''],
        47 => ['name' => 'DGC Albatros Landshut e.V.', 'shortName' => ''],
        48 => ['name' => 'DGCW Neidlingen e.V.', 'shortName' => ''],
        49 => ['name' => 'DGF Rhein-Mosel-Lahn e.V.', 'shortName' => ''],
        50 => ['name' => 'DGFC Rottal-Inn e.V.', 'shortName' => ''],
        51 => ['name' => 'DGFC Seeadler e.V.', 'shortName' => ''],
        52 => ['name' => 'DGFC Starzeln-Zollernalb e.V.', 'shortName' => ''],
        53 => ['name' => 'DHC Aalen e.V.', 'shortName' => ''],
        54 => ['name' => 'DHC Heidenheim e.V.', 'shortName' => ''],
        55 => ['name' => 'Die 1. Hohenhaslacher Flieger e.V.', 'shortName' => ''],
        56 => ['name' => 'Die Althofdrachen e.V.', 'shortName' => ''],
        57 => ['name' => 'Die Klippenspringer e.V.', 'shortName' => ''],
        58 => ['name' => 'Die Moselfalken e.V.', 'shortName' => ''],
        59 => ['name' => 'Diomedea Gleitschirmclub e.V.', 'shortName' => ''],
        60 => ['name' => 'Drachen- u. Gleitschirmclub Bayerwald e.V.', 'shortName' => ''],
        61 => ['name' => 'Drachen- u. Gleitschirmflieger Heilbronn e.V.', 'shortName' => ''],
        62 => ['name' => 'Drachen- u. Gleitschirmflieger Werdenfels e.V.', 'shortName' => ''],
        63 => ['name' => 'Drachen- u. Gleitschirmfliegerclub Battenberg e.V.', 'shortName' => ''],
        64 => ['name' => 'Drachen- u. Gleitschirmfliegerclub Suedschwarzwald e.V.', 'shortName' => ''],
        65 => ['name' => 'Drachen- u. Gleitschirmfliegerfreunde Berlin e.V.', 'shortName' => ''],
        66 => ['name' => 'Drachen- u. UL-Flieger SHA e.V.', 'shortName' => ''],
        67 => ['name' => 'Drachen- und Gleitschirmclub Airofun e.V.', 'shortName' => ''],
        68 => ['name' => 'Drachen- und Gleitschirmclub Loffenau e.V.', 'shortName' => ''],
        69 => ['name' => 'Drachen- und Gleitschirmflieger Bad Laasphe e.V.', 'shortName' => ''],
        70 => ['name' => 'Drachen- und Gleitschirmflieger Club Staufen e.V.', 'shortName' => ''],
        71 => ['name' => 'Drachen- und Gleitschirmflieger Hohenlohe e.V.', 'shortName' => ''],
        72 => ['name' => 'Drachen- und Gleitschirmflieger-Club Inzell e.V.', 'shortName' => ''],
        73 => ['name' => 'Drachen- und Gleitschirmfliegerclub Aschau', 'shortName' => ''],
        74 => ['name' => 'Drachen- und Gleitschirmfliegerclub Friedrichshafen e.V.', 'shortName' => ''],
        75 => ['name' => 'Drachen- und Gleitschirmfliegerclub Jena e.V.', 'shortName' => ''],
        76 => ['name' => 'Drachen- und Gleitschirmfliegerclub Osterzgebirge e.V.', 'shortName' => ''],
        77 => ['name' => 'Drachen- und Gleitschirmfliegerclub Regental e.V.', 'shortName' => ''],
        78 => ['name' => 'Drachen- und Gleitschirmfliegerclub Remstal e.V.', 'shortName' => ''],
        79 => ['name' => 'Drachen- und Gleitschirmfliegerclub Siebengebirge e.V.', 'shortName' => ''],
        80 => ['name' => 'Drachen- und Gleitschirmfliegerclub Tegernseer Tal e.V.', 'shortName' => ''],
        81 => ['name' => 'Drachen- und Gleitschirmfliegerclub Weser e.V.', 'shortName' => ''],
        82 => ['name' => 'Drachen- und Gleitschirmfliegergemeinschaft Alfeld e.V.', 'shortName' => ''],
        83 => ['name' => 'Drachen- und Gleitschirmfreunde Hellertal e.V.', 'shortName' => ''],
        84 => ['name' => 'Drachen- und Gleitschirmverein Baiersbronn e.V.', 'shortName' => ''],
        85 => ['name' => 'Drachen- und Gleitschirmverein Suedwuerttenberg-', 'shortName' => ''],
        86 => ['name' => 'Drachen- und Gleitsegelclub Loerzweiler e.V.', 'shortName' => ''],
        87 => ['name' => 'Drachen- und Gleitsegelclub Nahetal e.V.', 'shortName' => ''],
        88 => ['name' => 'Drachen- und Gleitsegelverein Goettingen e.V.', 'shortName' => ''],
        89 => ['name' => 'Drachen-Gleitschirmflieger-Club Hoexter e. V.', 'shortName' => ''],
        90 => ['name' => 'Drachen-u. Gleitschirmclub Frankfurt-Rhein-Main e.V.', 'shortName' => ''],
        91 => ['name' => 'Drachen-und Gleitschirmclub Hoyerswerda e.V.', 'shortName' => ''],
        92 => ['name' => 'Drachenflieger Bayr. Rigi e.V.', 'shortName' => ''],
        93 => ['name' => 'Drachenflieger Pohlheim e.V.', 'shortName' => ''],
        94 => ['name' => 'Drachenflieger-Club Mittenwald e.V.', 'shortName' => ''],
        95 => ['name' => 'Drachenflieger-Club Trier e.V.', 'shortName' => ''],
        96 => ['name' => 'Drachenfliegerclub Homburg', 'shortName' => ''],
        97 => ['name' => 'Drachenfliegerclub Bayrischzell e.V.', 'shortName' => ''],
        98 => ['name' => 'Drachenfliegerclub Drei-Kreis-Eck e.V.', 'shortName' => ''],
        99 => ['name' => 'Drachenfliegerclub Dreilaendereck e.V.', 'shortName' => ''],
        100 => ['name' => 'Drachenfliegerclub Goerauer Anger e.V.', 'shortName' => ''],
        101 => ['name' => 'Drachenfliegerclub Hammelburg e.V.', 'shortName' => ''],
        102 => ['name' => 'Drachenfliegerclub Hochries-Samerberg e.V.', 'shortName' => ''],
        103 => ['name' => 'Drachenfliegerclub Hohenneuffen e.V.', 'shortName' => ''],
        104 => ['name' => 'Drachenfliegerclub Ingolstadt e.V.', 'shortName' => ''],
        105 => ['name' => 'Drachenfliegerclub Isarwinkel e.V.', 'shortName' => ''],
        106 => ['name' => 'Drachenfliegerclub Kreis Olpe e.V.', 'shortName' => ''],
        107 => ['name' => 'Drachenfliegerclub Niederrhein e.V.', 'shortName' => ''],
        108 => ['name' => 'Drachenfliegerclub Vulkaneifel e.V.', 'shortName' => ''],
        109 => ['name' => 'Drachenfliegerverein Blumberg-Immendingen e.V.', 'shortName' => ''],
        110 => ['name' => 'Drachenfliegerverein Boesingen e.V.', 'shortName' => ''],
        111 => ['name' => 'Drachenfliegerverein Geislingen e.V.', 'shortName' => ''],
        112 => ['name' => 'Drachenfliegerverein Pfullingen e.V.', 'shortName' => ''],
        113 => ['name' => 'Drachenfliegerverein Spaichingen e.V.', 'shortName' => ''],
        114 => ['name' => 'Drachenflugclub Meissner e.V.', 'shortName' => ''],
        115 => ['name' => 'Drachenflugclub Saar e. V.', 'shortName' => ''],
        116 => ['name' => 'Drachenflugfreunde Fuerstenfeldbruck e.V.', 'shortName' => ''],
        117 => ['name' => 'Drachenfluggruppe Boerry Weserbergland e.V.', 'shortName' => ''],
        118 => ['name' => 'Drachenflugschule-Otto Lilienthal e.V.', 'shortName' => ''],
        119 => ['name' => 'Drachenflugverein Moskito e.V.', 'shortName' => ''],
        120 => ['name' => 'Ellerbacher Thermikfreunde e.V.', 'shortName' => ''],
        121 => ['name' => 'Elztalflieger e.V.', 'shortName' => ''],
        122 => ['name' => 'Enztalflieger Bad Wildbad e.V.', 'shortName' => ''],
        123 => ['name' => 'Fensterbachtaler Deltaclub e.V.', 'shortName' => ''],
        124 => ['name' => 'Fl-Aying Eagles e.V.', 'shortName' => ''],
        125 => ['name' => 'Flieger-Treff Rossbach/Wied e.V.', 'shortName' => ''],
        126 => ['name' => 'Fliegerclub Moeckern e.V.', 'shortName' => ''],
        127 => ['name' => 'Fliegergemeinschaft Daidalos e.V.', 'shortName' => ''],
        128 => ['name' => 'Fliegergemeinschaft Stauf e.V.', 'shortName' => ''],
        129 => ['name' => 'Fliegergruppe Riedlingen e.V.', 'shortName' => ''],
        130 => ['name' => 'Fliegerverein e.V. Walxheim', 'shortName' => ''],
        131 => ['name' => 'Flugfreunde Ulm / Donautal e.V.', 'shortName' => ''],
        132 => ['name' => 'Flugliebe e.V.', 'shortName' => ''],
        133 => ['name' => 'Flugsport-Lennetal e.V.', 'shortName' => ''],
        134 => ['name' => 'Flugsportfreunde Ourewaeller Iwwefliejer e.V.', 'shortName' => ''],
        135 => ['name' => 'Flugsportverein Bad Salzungen e.V.', 'shortName' => ''],
        136 => ['name' => 'Flugsportverein Gleitschirmfreunde Hartenrod e.V.', 'shortName' => ''],
        137 => ['name' => 'Flugsportverein Schwartenberg e.V.', 'shortName' => ''],
        138 => ['name' => 'Flugsportverein Windeckfalken Lauf e.V.', 'shortName' => ''],
        139 => ['name' => 'Flysports Weiden e.V.', 'shortName' => ''],
        140 => ['name' => 'Fraport AG Betriebssportgruppe-Luftsport', 'shortName' => ''],
        141 => ['name' => 'Freiflieger Niederrhein e.V.', 'shortName' => ''],
        142 => ['name' => 'FSC Franken e.V.', 'shortName' => ''],
        143 => ['name' => 'Fun Gliders Westerwald e.V.', 'shortName' => ''],
        144 => ['name' => 'Gasslerbergflieger e.V.', 'shortName' => ''],
        145 => ['name' => 'Gebaflieger e.V.', 'shortName' => ''],
        146 => ['name' => 'Gleitflieger Wehrheim e.V.', 'shortName' => ''],
        147 => ['name' => 'Gleitschirm Club Neckar-Odenwald e.V.', 'shortName' => ''],
        148 => ['name' => 'Gleitschirm Flieger Saar-Pfalz e.V.', 'shortName' => ''],
        149 => ['name' => 'Gleitschirm- und Drachenflieger Ostrau e.V.', 'shortName' => ''],
        150 => ['name' => 'Gleitschirm- und Drachenfliegerverein Schleswig-Holstein e.V. "Milan"', 'shortName' => 'Milan'],
        151 => ['name' => 'Gleitschirm- und Drachenflug e.V. Die Remstaeler', 'shortName' => ''],
        152 => ['name' => 'Gleitschirm- und Haengegleiter e.V. Drei-Kaiser-Berge Waldstetten', 'shortName' => ''],
        153 => ['name' => 'Gleitschirm-Club Kreuzberg Rhoen e.V.', 'shortName' => ''],
        154 => ['name' => 'Gleitschirm-Freunde Hochwald e.V.', 'shortName' => ''],
        155 => ['name' => 'Gleitschirmclub Borkies Sasbachwalden e.V.', 'shortName' => ''],
        156 => ['name' => 'Gleitschirmclub Skyline Westerwald e.V.', 'shortName' => ''],
        157 => ['name' => 'Gleitschirmclub Colditz e.V.', 'shortName' => ''],
        158 => ['name' => 'Gleitschirmclub Colibri Freiburg e.V.', 'shortName' => ''],
        159 => ['name' => 'Gleitschirmclub Fraenkische Schweiz e.V.', 'shortName' => ''],
        160 => ['name' => 'Gleitschirmclub Hochries-Samerberg e.V.', 'shortName' => ''],
        161 => ['name' => 'Gleitschirmclub Hochschwarzwald Muenstertal e.V.', 'shortName' => ''],
        162 => ['name' => 'Gleitschirmclub Inntal e.V.', 'shortName' => ''],
        163 => ['name' => 'Gleitschirmclub Kraichtal e.V.', 'shortName' => ''],
        164 => ['name' => 'Gleitschirmclub Lenticularis e.V.', 'shortName' => ''],
        165 => ['name' => 'Gleitschirmclub Markelsheim e.V.', 'shortName' => ''],
        166 => ['name' => 'Gleitschirmclub Nordhelle e.V.', 'shortName' => ''],
        167 => ['name' => 'Gleitschirmclub Oberschwaben', 'shortName' => ''],
        168 => ['name' => 'Gleitschirmclub Ratisbona e.V.', 'shortName' => ''],
        169 => ['name' => 'Gleitschirmclub Samtgemeinde Landesbergen e.V.', 'shortName' => ''],
        170 => ['name' => 'Gleitschirmclub SKYbavAIRia e.V.', 'shortName' => ''],
        171 => ['name' => 'Gleitschirmclub Suedheide e.V.', 'shortName' => ''],
        172 => ['name' => 'Gleitschirmclub Teutoburger Wald e.V.', 'shortName' => ''],
        173 => ['name' => 'Gleitschirmclub Wiesental e.V.', 'shortName' => ''],
        174 => ['name' => 'Gleitschirmflieger Lindenfels e.V.', 'shortName' => ''],
        175 => ['name' => 'Gleitschirmflieger Schwaney-Hoppenberg e.V.', 'shortName' => ''],
        176 => ['name' => 'Gleitschirmflieger Urenschwang e.V.', 'shortName' => ''],
        177 => ['name' => 'Gleitschirmflieger-Gemeinschaft Immenstadt-Sonthofen e.V', 'shortName' => ''],
        178 => ['name' => 'Gleitschirmflieger-MainSpessart e.V.', 'shortName' => ''],
        179 => ['name' => 'Gleitschirmfreunde Buehlertal-Buehl e.V.', 'shortName' => ''],
        180 => ['name' => 'Gleitschirmfreunde Kochel e.V.', 'shortName' => ''],
        181 => ['name' => 'Gleitschirmfreunde Taubertal e.V.', 'shortName' => ''],
        182 => ['name' => 'Gleitschirmfreunde Taunusstein 1995 e.V.', 'shortName' => ''],
        183 => ['name' => 'Gleitschirmfreunde Urbach e.V.', 'shortName' => ''],
        184 => ['name' => 'Gleitschirmjaeger-Saar e.V.', 'shortName' => ''],
        185 => ['name' => 'Gleitschirmverein Saaletal e.V.', 'shortName' => ''],
        186 => ['name' => 'Gleitschirmverein Baden e.V.', 'shortName' => ''],
        187 => ['name' => 'Gleitschirmverein Heuberg-Baar e.V.', 'shortName' => ''],
        188 => ['name' => 'Gleitschirmverein Nahe-Glan e.V.', 'shortName' => ''],
        189 => ['name' => 'Gleitschirmverein Rennsteig e.V.', 'shortName' => ''],
        190 => ['name' => 'Gleitsegelclub PARAOTIC Konstanz e.V.', 'shortName' => ''],
        191 => ['name' => 'Gleitsegelclub Frankenthermik e.V.', 'shortName' => ''],
        192 => ['name' => 'Gleitsegelclub Schwaebische Alb e.V.', 'shortName' => ''],
        193 => ['name' => 'Gleitsegelclub Weser e.V.', 'shortName' => ''],
        194 => ['name' => 'Gleitzeit e.V.', 'shortName' => ''],
        195 => ['name' => 'Govertical', 'shortName' => ''],
        196 => ['name' => 'Grenzlandflieger-FRG e.V.', 'shortName' => ''],
        197 => ['name' => 'GSC Albatros Bad Reichenhall e.V.', 'shortName' => ''],
        198 => ['name' => 'Hamburger Drachen- und Gleitschirmflieger', 'shortName' => 'HDGF'],
        199 => ['name' => 'Haengegleiter Club Region Blauen e.V.', 'shortName' => ''],
        200 => ['name' => 'Haengegleiter Schleppverein Nix wie Nuff Offenbach e. V.', 'shortName' => ''],
        201 => ['name' => 'Haengegleiter-Club Einkorn Schwaebisch Hall e.V.', 'shortName' => ''],
        202 => ['name' => 'Harzer Drachen- und Gleitschirm-Verein Goslar e.V.(HDGV)', 'shortName' => ''],
        203 => ['name' => 'Hesselbergflieger e.V.', 'shortName' => ''],
        204 => ['name' => 'Hochfelln-Flieger Bergen e.V.', 'shortName' => ''],
        205 => ['name' => 'Hoernle-Pilotenclub', 'shortName' => ''],
        206 => ['name' => 'Hot Sport Sportschulen GmbH', 'shortName' => ''],
        207 => ['name' => 'IFG Gleitschirmclub Ravensburg e.V.', 'shortName' => ''],
        208 => ['name' => 'IG Parawinch e.V.', 'shortName' => ''],
        209 => ['name' => 'Ilmtal-Flieger e.V.', 'shortName' => ''],
        210 => ['name' => 'Initiative Fraenkischer Gleitschirmflieger', 'shortName' => ''],
        211 => ['name' => 'Jura Airlines Albatros e.V.', 'shortName' => ''],
        212 => ['name' => 'Kleinwalsertaler Drachenflieger e.V.', 'shortName' => ''],
        213 => ['name' => 'Kurpfaelzer Gleitschirmflieger Heidelberg e.V.', 'shortName' => ''],
        214 => ['name' => 'Lattenberger Flugsaurier e.V.', 'shortName' => ''],
        215 => ['name' => 'Leichtflieger-Oberlausitz e.V.', 'shortName' => ''],
        216 => ['name' => 'Lenggrieser Gleitschirmflieger e.V.', 'shortName' => ''],
        217 => ['name' => 'Lilienthal-Gleiter-Unterfranken e.V.', 'shortName' => ''],
        218 => ['name' => 'Luftsportclub Bayer Leverkusen e.V.', 'shortName' => ''],
        219 => ['name' => 'Luftsportgemeinschaft Bienwald-Falken e.V.', 'shortName' => ''],
        220 => ['name' => 'Luftsportgemeinschaft Harz', 'shortName' => ''],
        221 => ['name' => 'Luftsportverein Alsfeld e.V.', 'shortName' => ''],
        222 => ['name' => 'Luftsportverein Crawinkel e.V.', 'shortName' => ''],
        223 => ['name' => 'Luftsportverein Egge e.V.', 'shortName' => ''],
        224 => ['name' => 'Luftsportverein Neuseenland e.V.', 'shortName' => ''],
        225 => ['name' => 'Luftsportverein Neustadt Glewe e.V.', 'shortName' => ''],
        226 => ['name' => 'Luftsportverein Parchim e.V.', 'shortName' => ''],
        227 => ['name' => 'Luftsportverein Torgau-Beilrode e.V.', 'shortName' => ''],
        228 => ['name' => 'Luftsportverein Zeitz e.V.', 'shortName' => ''],
        229 => ['name' => 'Luftsportvereinigung Greiling e.V.', 'shortName' => ''],
        230 => ['name' => 'Main-Taunus-Flug Dauborn e.V.', 'shortName' => ''],
        231 => ['name' => 'Mittag team e.V. Immenstadt', 'shortName' => ''],
        232 => ['name' => 'Motorschirmfreunde-Pfalz e.V.', 'shortName' => ''],
        233 => ['name' => 'MuenstAIRland-GS-u. HG Verein', 'shortName' => ''],
        234 => ['name' => 'Naturfreunde und Freiflieger Grosser', 'shortName' => ''],
        235 => ['name' => 'Nordbayerische Drachenflieger e.V.', 'shortName' => ''],
        236 => ['name' => 'Nordhessischer Gleitschirm-Club Kassel e.V.', 'shortName' => ''],
        237 => ['name' => 'Oase-Pilotenclub', 'shortName' => ''],
        238 => ['name' => 'Oberfraenkischer Haengegleiter Verein Coburg e.V.', 'shortName' => ''],
        239 => ['name' => 'Oberstdorfer Drachen- und Gleitschirmflieger e.V.', 'shortName' => ''],
        240 => ['name' => 'OFS-Pilotenclub', 'shortName' => ''],
        241 => ['name' => 'Oppenauer Gleitschirmflieger e.V.', 'shortName' => ''],
        242 => ['name' => 'Ortenauer Drachen- und Gleitschirmflieger e.V.', 'shortName' => ''],
        243 => ['name' => 'Ostallgaeuer Gleitschirmflieger e.V.', 'shortName' => ''],
        244 => ['name' => 'Ostrachtaler Gleitschirmflieger e.V.', 'shortName' => ''],
        245 => ['name' => 'Ostthueringer Drachen- u. Gleitschirmfliegerverein e.V.', 'shortName' => ''],
        246 => ['name' => 'Ostwindfreunde e.V.', 'shortName' => ''],
        247 => ['name' => 'Para-Air Augsburg West e.V.', 'shortName' => ''],
        248 => ['name' => 'Paraclub Kressberg', 'shortName' => ''],
        249 => ['name' => 'Parafly Franken e.V.', 'shortName' => ''],
        250 => ['name' => 'Paragleiter- und Delta Flugsportverein Engstingen e.V.', 'shortName' => ''],
        251 => ['name' => 'Paragliding Hof/Saale Drachen-u. Gleitschirm-Windengemeinschaft e.V.', 'shortName' => ''],
        252 => ['name' => 'Paragliding Nordwest e.V.', 'shortName' => ''],
        253 => ['name' => 'Paragliding-West e.V.', 'shortName' => ''],
        254 => ['name' => 'PC Werratal-Eschwege-Eichsfeld e.V.', 'shortName' => ''],
        255 => ['name' => 'Pfaelzer Gleitschirm Club e.V.', 'shortName' => ''],
        256 => ['name' => 'Pfrontener Falken e.V.', 'shortName' => ''],
        257 => ['name' => 'Rhoener Drachen- u. Gleitschirmflieger Poppenhausen e.V.', 'shortName' => ''],
        258 => ['name' => 'Ruhrpott-Paragliding e.V.', 'shortName' => ''],
        259 => ['name' => 'Sauerlandair e.V.', 'shortName' => ''],
        260 => ['name' => 'Schleppgemeinschaft Bergstrasse e.V.', 'shortName' => ''],
        261 => ['name' => 'Schleppgemeinschaft Uelhof e.V.', 'shortName' => ''],
        262 => ['name' => 'Schleppteam Wilder Sueden', 'shortName' => ''],
        263 => ['name' => 'Schrattenbach Flieger e.V.', 'shortName' => ''],
        264 => ['name' => 'Schwaebischer Albverein OG Schrozberg e.V.', 'shortName' => ''],
        265 => ['name' => 'Schwangauer Drachenflieger e.V.', 'shortName' => ''],
        266 => ['name' => 'Schweinfurter Gleitschirmfreunde e.V.', 'shortName' => ''],
        267 => ['name' => 'SG Stern Deutschland e.V.', 'shortName' => ''],
        268 => ['name' => 'SG Stern Rastatt', 'shortName' => ''],
        269 => ['name' => 'SG-Stern Gaggenau', 'shortName' => ''],
        270 => ['name' => 'SG-Stern Woerth/Germersheim in SG-', 'shortName' => ''],
        271 => ['name' => 'Silent Wings Gleitschirmclub e.V.', 'shortName' => ''],
        272 => ['name' => 'Sindelfinger Drachen- u. Gleitschirmflieger e.V.', 'shortName' => ''],
        273 => ['name' => 'SkyTeam-Neuss e.V.', 'shortName' => ''],
        274 => ['name' => 'Spiesshornfalken Bernau e.V.', 'shortName' => ''],
        275 => ['name' => 'Suedpfaelzer Gleitschirmflieger Club e.V.', 'shortName' => ''],
        276 => ['name' => 'SV Oberes Banfetal e.V.', 'shortName' => ''],
        277 => ['name' => 'SV-Schnathorst 1925 e.V.', 'shortName' => ''],
        278 => ['name' => 'Taelesflieger Deggingen e.V.', 'shortName' => ''],
        279 => ['name' => 'Thermik-Flieger Flying Turtles e.V.', 'shortName' => ''],
        280 => ['name' => 'TSV Seissen Drachenflieger e.V.', 'shortName' => ''],
        281 => ['name' => 'Turbu-Lenzen Isental e.V.', 'shortName' => ''],
        282 => ['name' => 'Turnverein Bissingen e.V.', 'shortName' => ''],
        283 => ['name' => 'Ultraleicht- und Drachenfliegerclub Forst Sengenthal e.V.', 'shortName' => ''],
        284 => ['name' => 'Warener Luftsportverein e.V.', 'shortName' => ''],
        285 => ['name' => 'Warsteiner Skyglider Team e.V.', 'shortName' => ''],
        286 => ['name' => 'Westallgaeuer Drachen- und Gleitschirmflieger e.V.', 'shortName' => ''],
        287 => ['name' => 'Westallgaeuer Thermikzipfel e.V.', 'shortName' => ''],
        288 => ['name' => 'Windenclub Eifelthermik', 'shortName' => ''],
        289 => ['name' => 'Windengemeinschaft Sky Rider e.V.', 'shortName' => ''],
        290 => ['name' => 'Wippertaler Drachenflugverein e.V.', 'shortName' => ''],
        291 => ['name' => 'Wolkenkratzer e.V.', 'shortName' => ''],
        292 => ['name' => 'Parateam-Pannonia e.V.', 'shortName' => ''],
        293 => ['name' => 'Sky Club Austria e.V.', 'shortName' => ''],
    ]
];
