<option value="Kein Verein">Ich bin in keinem Verein</option>
<option value="08/15 Parajumpers e.V.">08/15 Parajumpers e.V.</option>
<option value="1. Bamberger Gleitschirm Club e.V.">1. Bamberger Gleitschirm Club e.V.</option>
<option value="1. Cottbuser Drachen- und Gleitschirmfliegerclub e.V.">1. Cottbuser Drachen- und Gleitschirmfliegerclub e.V.</option>
<option value="1. Drachen-und Gleitschirmclub Jura Altmuehltal e.V.">1. Drachen-und Gleitschirmclub Jura Altmuehltal e.V.</option>
<option value="1. Drachenfliegerclub Sachsen e.V.">1. Drachenfliegerclub Sachsen e.V.</option>
<option value="1. Drachenflugclub Wasserkuppe e.V.">1. Drachenflugclub Wasserkuppe e.V.</option>
<option value="1. Gleitschirmverein Bayerwald e.V.">1. Gleitschirmverein Bayerwald e.V.</option>
<option value="1. Harsberger Gleitschirm- u. Drachenclub Lauterbach e.V.">1. Harsberger Gleitschirm- u. Drachenclub Lauterbach e.V.</option>
<option value="1. Oberpfaelzer Drachenfliegerclub Riedenburg e.V.">1. Oberpfaelzer Drachenfliegerclub Riedenburg e.V.</option>
<option value="1. Odenwaelder Drachen- u. Gleitschirmflieger-Club e.V.">1. Odenwaelder Drachen- u. Gleitschirmflieger-Club e.V.</option>
<option value="1. Para-Ski-Club Saar e.V.">1. Para-Ski-Club Saar e.V.</option>
<option value="1. Parafly-Club Schwaben e.V.">1. Parafly-Club Schwaben e.V.</option>
<option value="1. Pfaelzer Drachen-u. Gleitschirmfliegerclub e.V.">1. Pfaelzer Drachen-u. Gleitschirmfliegerclub e.V.</option>
<option value="AERO Club Altena-Hegenscheid e.V.">AERO Club Altena-Hegenscheid e.V.</option>
<option value="Air Team Neuss e.V.">Air Team Neuss e.V.</option>
<option value="Airbus-Sportgemeinschaft Ottobrunn e.V.">Airbus-Sportgemeinschaft Ottobrunn e.V.</option>
<option value="Airwalker e.V.">Airwalker e.V.</option>
<option value="Albatros-Gleitsegelclub Aschaffenburg e.V.">Albatros-Gleitsegelclub Aschaffenburg e.V.</option>
<option value="Alpspitzflieger e.V.">Alpspitzflieger e.V.</option>
<option value="Ammergauer Drachen- und Gleitschirmflieger e.V.">Ammergauer Drachen- und Gleitschirmflieger e.V.</option>
<option value="Asslarer Gleitschirmflieger e.V.">Asslarer Gleitschirmflieger e.V.</option>
<option value="Aufwind-Brettachtal e.V.">Aufwind-Brettachtal e.V.</option>
<option value="Aufwindfreunde e.V.">Aufwindfreunde e.V.</option>
<option value="Augsburger Drachenflieger e.V.">Augsburger Drachenflieger e.V.</option>
<option value="Baarflieger Fuerstenberg-Geisingen e.V.">Baarflieger Fuerstenberg-Geisingen e.V.</option>
<option value="Berchtesgadener Drachenflieger e.V.">Berchtesgadener Drachenflieger e.V.</option>
<option value="Berchtesgadener Gleitschirmflieger e.V.">Berchtesgadener Gleitschirmflieger e.V.</option>
<option value="Bergdohlen Brannenburg e.V.">Bergdohlen Brannenburg e.V.</option>
<option value="Bergstraessler Drachenflieger e.V.">Bergstraessler Drachenflieger e.V.</option>
<option value="Bodenlos e.V.">Bodenlos e.V.</option>
<option value="Club fuer Drachenflugsport e.V. Hardheim">Club fuer Drachenflugsport e.V. Hardheim</option>
<option value="Condor e.V. zur Foerderung des Gleitschirmfliegens">Condor e.V. zur Foerderung des Gleitschirmfliegens</option>
<option value="d'Allgaeuer Drachenflieger e.V.">d'Allgaeuer Drachenflieger e.V.</option>
<option value="D'Schwoba Schwaebische Drachenflieger Erbach e.V.">D'Schwoba Schwaebische Drachenflieger Erbach e.V.</option>
<option value="d'Waelder Drachenflieger e.V.">d'Waelder Drachenflieger e.V.</option>
<option value="Deisterflieger e.V.">Deisterflieger e.V.</option>
<option value="Delta Club Bavaria Ruhpolding e.V.">Delta Club Bavaria Ruhpolding e.V.</option>
<option value="Delta Club Condor e.V. (Wehr)">Delta Club Condor e.V. (Wehr)</option>
<option value="Delta Flug Todtnau e.V.">Delta Flug Todtnau e.V.</option>
<option value="Delta-Club Ith e.V.">Delta-Club Ith e.V.</option>
<option value="Delta-Club Mosbach e.V.">Delta-Club Mosbach e.V.</option>
<option value="Delta-Club Rheinland e.V.">Delta-Club Rheinland e.V.</option>
<option value="Delta-Club Wiehengebirge e.V.">Delta-Club Wiehengebirge e.V.</option>
<option value="Deltaclub Teutoburger Wald e.V.">Deltaclub Teutoburger Wald e.V.</option>
<option value="Der Flieger Club Achental e.V.">Der Flieger Club Achental e.V.</option>
<option value="DFC u. GSC im Luftsportverein Laucha-Dorndorf e.V.">DFC u. GSC im Luftsportverein Laucha-Dorndorf e.V.</option>
<option value="DGC Albatros Landshut e.V.">DGC Albatros Landshut e.V.</option>
<option value="DGCW Neidlingen e.V.">DGCW Neidlingen e.V.</option>
<option value="DGF Rhein-Mosel-Lahn e.V.">DGF Rhein-Mosel-Lahn e.V.</option>
<option value="DGFC Rottal-Inn e.V.">DGFC Rottal-Inn e.V.</option>
<option value="DGFC Seeadler e.V.">DGFC Seeadler e.V.</option>
<option value="DGFC Starzeln-Zollernalb e.V.">DGFC Starzeln-Zollernalb e.V.</option>
<option value="DHC Aalen e.V.">DHC Aalen e.V.</option>
<option value="DHC Heidenheim e.V.">DHC Heidenheim e.V.</option>
<option value="Die 1. Hohenhaslacher Flieger e.V.">Die "1. Hohenhaslacher Flieger" e.V.</option>
<option value="Die Althofdrachen e.V.">Die Althofdrachen e.V.</option>
<option value="Die Klippenspringer e.V.">Die Klippenspringer e.V.</option>
<option value="Die Moselfalken e.V.">Die Moselfalken e.V.</option>
<option value="Diomedea Gleitschirmclub e.V.">Diomedea Gleitschirmclub e.V.</option>
<option value="Drachen- u. Gleitschirmclub Bayerwald e.V.">Drachen- u. Gleitschirmclub Bayerwald e.V.</option>
<option value="Drachen- u. Gleitschirmflieger Heilbronn e.V.">Drachen- u. Gleitschirmflieger Heilbronn e.V.</option>
<option value="Drachen- u. Gleitschirmflieger Werdenfels e.V.">Drachen- u. Gleitschirmflieger Werdenfels e.V.</option>
<option value="Drachen- u. Gleitschirmfliegerclub Battenberg e.V.">Drachen- u. Gleitschirmfliegerclub Battenberg e.V.</option>
<option value="Drachen- u. Gleitschirmfliegerclub Suedschwarzwald e.V.">Drachen- u. Gleitschirmfliegerclub Suedschwarzwald e.V.</option>
<option value="Drachen- u. Gleitschirmfliegerfreunde Berlin e.V.">Drachen- u. Gleitschirmfliegerfreunde Berlin e.V.</option>
<option value="Drachen- u. UL-Flieger SHA e.V.">Drachen- u. UL-Flieger SHA e.V.</option>
<option value="Drachen- und Gleitschirmclub Airofun e.V.">Drachen- und Gleitschirmclub Airofun e.V.</option>
<option value="Drachen- und Gleitschirmclub Loffenau e.V.">Drachen- und Gleitschirmclub Loffenau e.V.</option>
<option value="Drachen- und Gleitschirmflieger Bad Laasphe e.V.">Drachen- und Gleitschirmflieger Bad Laasphe e.V.</option>
<option value="Drachen- und Gleitschirmflieger Club Staufen e.V.">Drachen- und Gleitschirmflieger Club Staufen e.V.</option>
<option value="Drachen- und Gleitschirmflieger Hohenlohe e.V.">Drachen- und Gleitschirmflieger Hohenlohe e.V.</option>
<option value="Drachen- und Gleitschirmflieger-Club Inzell e.V.">Drachen- und Gleitschirmflieger-Club Inzell e.V.</option>
<option value="Drachen- und Gleitschirmfliegerclub Aschau">Drachen- und Gleitschirmfliegerclub Aschau</option>
<option value="Drachen- und Gleitschirmfliegerclub Friedrichshafen e.V.">Drachen- und Gleitschirmfliegerclub Friedrichshafen e.V.</option>
<option value="Drachen- und Gleitschirmfliegerclub Jena e.V.">Drachen- und Gleitschirmfliegerclub Jena e.V.</option>
<option value="Drachen- und Gleitschirmfliegerclub Osterzgebirge e.V.">Drachen- und Gleitschirmfliegerclub Osterzgebirge e.V.</option>
<option value="Drachen- und Gleitschirmfliegerclub Regental e.V.">Drachen- und Gleitschirmfliegerclub Regental e.V.</option>
<option value="Drachen- und Gleitschirmfliegerclub Remstal e.V.">Drachen- und Gleitschirmfliegerclub Remstal e.V.</option>
<option value="Drachen- und Gleitschirmfliegerclub Siebengebirge e.V.">Drachen- und Gleitschirmfliegerclub Siebengebirge e.V.</option>
<option value="Drachen- und Gleitschirmfliegerclub Tegernseer Tal e.V.">Drachen- und Gleitschirmfliegerclub Tegernseer Tal e.V.</option>
<option value="Drachen- und Gleitschirmfliegerclub Weser e.V.">Drachen- und Gleitschirmfliegerclub Weser e.V.</option>
<option value="Drachen- und Gleitschirmfliegergemeinschaft Alfeld e.V.">Drachen- und Gleitschirmfliegergemeinschaft Alfeld e.V.</option>
<option value="Drachen- und Gleitschirmfreunde Hellertal e.V.">Drachen- und Gleitschirmfreunde Hellertal e.V.</option>
<option value="Drachen- und Gleitschirmverein Baiersbronn e.V.">Drachen- und Gleitschirmverein Baiersbronn e.V.</option>
<option value="Drachen- und Gleitschirmverein Suedwuerttenberg-">Drachen- und Gleitschirmverein Suedwuerttenberg-</option>
<option value="Drachen- und Gleitsegelclub Loerzweiler e.V.">Drachen- und Gleitsegelclub Loerzweiler e.V.</option>
<option value="Drachen- und Gleitsegelclub Nahetal e.V.">Drachen- und Gleitsegelclub Nahetal e.V.</option>
<option value="Drachen- und Gleitsegelverein Goettingen e.V.">Drachen- und Gleitsegelverein Goettingen e.V.</option>
<option value="Drachen-Gleitschirmflieger-Club Hoexter e. V.">Drachen-Gleitschirmflieger-Club Hoexter e. V.</option>
<option value="Drachen-u. Gleitschirmclub Frankfurt-Rhein-Main e.V.">Drachen-u. Gleitschirmclub Frankfurt-Rhein-Main e.V.</option>
<option value="Drachen-und Gleitschirmclub Hoyerswerda e.V.">Drachen-und Gleitschirmclub Hoyerswerda e.V.</option>
<option value="Drachenflieger Bayr. Rigi e.V.">Drachenflieger Bayr. Rigi e.V.</option>
<option value="Drachenflieger Pohlheim e.V.">Drachenflieger Pohlheim e.V.</option>
<option value="Drachenflieger-Club Mittenwald e.V.">Drachenflieger-Club Mittenwald e.V.</option>
<option value="Drachenflieger-Club Trier e.V.">Drachenflieger-Club Trier e.V.</option>
<option value="Drachenfliegerclub Homburg">Drachenfliegerclub "Homburg"</option>
<option value="Drachenfliegerclub Bayrischzell e.V.">Drachenfliegerclub Bayrischzell e.V.</option>
<option value="Drachenfliegerclub Drei-Kreis-Eck e.V.">Drachenfliegerclub Drei-Kreis-Eck e.V.</option>
<option value="Drachenfliegerclub Dreilaendereck e.V.">Drachenfliegerclub Dreilaendereck e.V.</option>
<option value="Drachenfliegerclub Goerauer Anger e.V.">Drachenfliegerclub Goerauer Anger e.V.</option>
<option value="Drachenfliegerclub Hammelburg e.V.">Drachenfliegerclub Hammelburg e.V.</option>
<option value="Drachenfliegerclub Hochries-Samerberg e.V.">Drachenfliegerclub Hochries-Samerberg e.V.</option>
<option value="Drachenfliegerclub Hohenneuffen e.V.">Drachenfliegerclub Hohenneuffen e.V.</option>
<option value="Drachenfliegerclub Ingolstadt e.V.">Drachenfliegerclub Ingolstadt e.V.</option>
<option value="Drachenfliegerclub Isarwinkel e.V.">Drachenfliegerclub Isarwinkel e.V.</option>
<option value="Drachenfliegerclub Kreis Olpe e.V.">Drachenfliegerclub Kreis Olpe e.V.</option>
<option value="Drachenfliegerclub Niederrhein e.V.">Drachenfliegerclub Niederrhein e.V.</option>
<option value="Drachenfliegerclub Vulkaneifel e.V.">Drachenfliegerclub Vulkaneifel e.V.</option>
<option value="Drachenfliegerverein Blumberg-Immendingen e.V.">Drachenfliegerverein Blumberg-Immendingen e.V.</option>
<option value="Drachenfliegerverein Boesingen e.V.">Drachenfliegerverein Boesingen e.V.</option>
<option value="Drachenfliegerverein Geislingen e.V.">Drachenfliegerverein Geislingen e.V.</option>
<option value="Drachenfliegerverein Pfullingen e.V.">Drachenfliegerverein Pfullingen e.V.</option>
<option value="Drachenfliegerverein Spaichingen e.V.">Drachenfliegerverein Spaichingen e.V.</option>
<option value="Drachenflugclub Meissner e.V.">Drachenflugclub Meissner e.V.</option>
<option value="Drachenflugclub Saar e. V.">Drachenflugclub Saar e. V.</option>
<option value="Drachenflugfreunde Fuerstenfeldbruck e.V.">Drachenflugfreunde Fuerstenfeldbruck e.V.</option>
<option value="Drachenfluggruppe Boerry Weserbergland e.V.">Drachenfluggruppe Boerry Weserbergland e.V.</option>
<option value="Drachenflugschule-Otto Lilienthal e.V.">Drachenflugschule-Otto Lilienthal e.V.</option>
<option value="Drachenflugverein Moskito e.V.">Drachenflugverein Moskito e.V.</option>
<option value="Ellerbacher Thermikfreunde e.V.">Ellerbacher Thermikfreunde e.V.</option>
<option value="Elztalflieger e.V.">Elztalflieger e.V.</option>
<option value="Enztalflieger Bad Wildbad e.V.">Enztalflieger Bad Wildbad e.V.</option>
<option value="Fensterbachtaler Deltaclub e.V.">Fensterbachtaler Deltaclub e.V.</option>
<option value="Fl-Aying Eagles e.V.">Fl-Aying Eagles e.V.</option>
<option value="Flieger-Treff Rossbach/Wied e.V.">Flieger-Treff Rossbach/Wied e.V.</option>
<option value="Fliegerclub Moeckern e.V.">Fliegerclub Moeckern e.V.</option>
<option value="Fliegergemeinschaft Daidalos e.V.">Fliegergemeinschaft Daidalos e.V.</option>
<option value="Fliegergemeinschaft Stauf e.V.">Fliegergemeinschaft Stauf e.V.</option>
<option value="Fliegergruppe Riedlingen e.V.">Fliegergruppe Riedlingen e.V.</option>
<option value="Fliegerverein e.V. Walxheim">Fliegerverein e.V. Walxheim</option>
<option value="Flugfreunde Ulm / Donautal e.V.">Flugfreunde Ulm / Donautal e.V.</option>
<option value="Flugliebe e.V.">Flugliebe e.V.</option>
<option value="Flugsport-Lennetal e.V.">Flugsport-Lennetal e.V.</option>
<option value="Flugsportfreunde Ourewaeller Iwwefliejer e.V.">Flugsportfreunde "Ourewaeller Iwwefliejer" e.V.</option>
<option value="Flugsportverein Bad Salzungen e.V.">Flugsportverein Bad Salzungen e.V.</option>
<option value="Flugsportverein Gleitschirmfreunde Hartenrod e.V.">Flugsportverein Gleitschirmfreunde Hartenrod e.V.</option>
<option value="Flugsportverein Schwartenberg e.V.">Flugsportverein Schwartenberg e.V.</option>
<option value="Flugsportverein Windeckfalken Lauf e.V.">Flugsportverein Windeckfalken Lauf e.V.</option>
<option value="Flysports Weiden e.V.">Flysports Weiden e.V.</option>
<option value="Fraport AG Betriebssportgruppe-Luftsport">Fraport AG Betriebssportgruppe-Luftsport</option>
<option value="Freiflieger Niederrhein e.V.">Freiflieger Niederrhein e.V.</option>
<option value="FSC Franken e.V.">FSC Franken e.V.</option>
<option value="Fun Gliders Westerwald e.V.">Fun Gliders Westerwald e.V.</option>
<option value="Gasslerbergflieger e.V.">Gasslerbergflieger e.V.</option>
<option value="Gebaflieger e.V.">Gebaflieger e.V.</option>
<option value="Gleitflieger Wehrheim e.V.">Gleitflieger Wehrheim e.V.</option>
<option value="Gleitschirm Club Neckar-Odenwald e.V.">Gleitschirm Club Neckar-Odenwald e.V.</option>
<option value="Gleitschirm Flieger Saar-Pfalz e.V.">Gleitschirm Flieger Saar-Pfalz e.V.</option>
<option value="Gleitschirm- und Drachenflieger Ostrau e.V.">Gleitschirm- und Drachenflieger Ostrau e.V.</option>
<option value="Gleitschirm- und Drachenfliegerverein Schleswig-Holstein e.V.">Gleitschirm- und Drachenfliegerverein Schleswig-Holstein e.V. "Milan"</option>
<option value="Gleitschirm- und Drachenflug e.V. Die Remstaeler">Gleitschirm- und Drachenflug e.V. Die Remstaeler</option>
<option value="Gleitschirm- und Haengegleiter e.V. Drei-Kaiser-Berge Waldstetten">Gleitschirm- und Haengegleiter e.V. Drei-Kaiser-Berge Waldstetten</option>
<option value="Gleitschirm-Club Kreuzberg Rhoen e.V.">Gleitschirm-Club Kreuzberg Rhoen e.V.</option>
<option value="Gleitschirm-Freunde Hochwald e.V.">Gleitschirm-Freunde Hochwald e.V.</option>
<option value="Gleitschirmclub Borkies Sasbachwalden e.V.">Gleitschirmclub "Borkies" Sasbachwalden e.V.</option>
<option value="Gleitschirmclub Skyline Westerwald e.V.">Gleitschirmclub "Skyline" Westerwald e.V.</option>
<option value="Gleitschirmclub Colditz e.V.">Gleitschirmclub Colditz e.V.</option>
<option value="Gleitschirmclub Colibri Freiburg e.V.">Gleitschirmclub Colibri Freiburg e.V.</option>
<option value="Gleitschirmclub Fraenkische Schweiz e.V.">Gleitschirmclub Fraenkische Schweiz e.V.</option>
<option value="Gleitschirmclub Hochries-Samerberg e.V.">Gleitschirmclub Hochries-Samerberg e.V.</option>
<option value="Gleitschirmclub Hochschwarzwald Muenstertal e.V.">Gleitschirmclub Hochschwarzwald Muenstertal e.V.</option>
<option value="Gleitschirmclub Inntal e.V.">Gleitschirmclub Inntal e.V.</option>
<option value="Gleitschirmclub Kraichtal e.V.">Gleitschirmclub Kraichtal e.V.</option>
<option value="Gleitschirmclub Lenticularis e.V.">Gleitschirmclub Lenticularis e.V.</option>
<option value="Gleitschirmclub Markelsheim e.V.">Gleitschirmclub Markelsheim e.V.</option>
<option value="Gleitschirmclub Nordhelle e.V.">Gleitschirmclub Nordhelle e.V.</option>
<option value="Gleitschirmclub Oberschwaben">Gleitschirmclub Oberschwaben</option>
<option value="Gleitschirmclub Ratisbona e.V.">Gleitschirmclub Ratisbona e.V.</option>
<option value="Gleitschirmclub Samtgemeinde Landesbergen e.V.">Gleitschirmclub Samtgemeinde Landesbergen e.V.</option>
<option value="Gleitschirmclub SKYbavAIRia e.V.">Gleitschirmclub SKYbavAIRia e.V.</option>
<option value="Gleitschirmclub Suedheide e.V.">Gleitschirmclub Suedheide e.V.</option>
<option value="Gleitschirmclub Teutoburger Wald e.V.">Gleitschirmclub Teutoburger Wald e.V.</option>
<option value="Gleitschirmclub Wiesental e.V.">Gleitschirmclub Wiesental e.V.</option>
<option value="Gleitschirmflieger Lindenfels e.V.">Gleitschirmflieger Lindenfels e.V.</option>
<option value="Gleitschirmflieger Schwaney-Hoppenberg e.V.">Gleitschirmflieger Schwaney-Hoppenberg e.V.</option>
<option value="Gleitschirmflieger Urenschwang e.V.">Gleitschirmflieger Urenschwang e.V.</option>
<option value="Gleitschirmflieger-Gemeinschaft Immenstadt-Sonthofen e.V">Gleitschirmflieger-Gemeinschaft Immenstadt-Sonthofen e.V</option>
<option value="Gleitschirmflieger-MainSpessart e.V.">Gleitschirmflieger-MainSpessart e.V.</option>
<option value="Gleitschirmfreunde Buehlertal-Buehl e.V.">Gleitschirmfreunde Buehlertal-Buehl e.V.</option>
<option value="Gleitschirmfreunde Kochel e.V.">Gleitschirmfreunde Kochel e.V.</option>
<option value="Gleitschirmfreunde Taubertal e.V.">Gleitschirmfreunde Taubertal e.V.</option>
<option value="Gleitschirmfreunde Taunusstein 1995 e.V.">Gleitschirmfreunde Taunusstein 1995 e.V.</option>
<option value="Gleitschirmfreunde Urbach e.V.">Gleitschirmfreunde Urbach e.V.</option>
<option value="Gleitschirmjaeger-Saar e.V.">Gleitschirmjaeger-Saar e.V.</option>
<option value="Gleitschirmverein Saaletal e.V.">Gleitschirmverein "Saaletal e.V."</option>
<option value="Gleitschirmverein Baden e.V.">Gleitschirmverein Baden e.V.</option>
<option value="Gleitschirmverein Heuberg-Baar e.V.">Gleitschirmverein Heuberg-Baar e.V.</option>
<option value="Gleitschirmverein Nahe-Glan e.V.">Gleitschirmverein Nahe-Glan e.V.</option>
<option value="Gleitschirmverein Rennsteig e.V.">Gleitschirmverein Rennsteig e.V.</option>
<option value="Gleitsegelclub PARAOTIC Konstanz e.V.">Gleitsegelclub "PARAOTIC" Konstanz e.V.</option>
<option value="Gleitsegelclub Frankenthermik e.V.">Gleitsegelclub Frankenthermik e.V.</option>
<option value="Gleitsegelclub Schwaebische Alb e.V.">Gleitsegelclub Schwaebische Alb e.V.</option>
<option value="Gleitsegelclub Weser e.V.">Gleitsegelclub Weser e.V.</option>
<option value="Gleitzeit e.V.">Gleitzeit e.V.</option>
<option value="Govertical">Govertical</option>
<option value="Grenzlandflieger-FRG e.V.">Grenzlandflieger-FRG e.V.</option>
<option value="GSC Albatros Bad Reichenhall e.V.">GSC "Albatros" Bad Reichenhall e.V.</option>
<option value="HDGF">Hamburger Drachen- und Gleitschirmflieger e.V.</option>
<option value="Haengegleiter Club Region Blauen e.V.">Haengegleiter Club Region Blauen e.V.</option>
<option value="Haengegleiter Schleppverein Nix wie Nuff Offenbach e. V.">Haengegleiter Schleppverein "Nix wie Nuff" Offenbach e. V.</option>
<option value="Haengegleiter-Club Einkorn Schwaebisch Hall e.V.">Haengegleiter-Club "Einkorn Schwaebisch Hall" e.V.</option>
<option value="Harzer Drachen- und Gleitschirm-Verein Goslar e.V.(HDGV)">Harzer Drachen- und Gleitschirm-Verein Goslar e.V.(HDGV)</option>
<option value="Hesselbergflieger e.V.">Hesselbergflieger e.V.</option>
<option value="Hochfelln-Flieger Bergen e.V.">Hochfelln-Flieger Bergen e.V.</option>
<option value="Hoernle-Pilotenclub">Hoernle-Pilotenclub</option>
<option value="Hot Sport Sportschulen GmbH">Hot Sport Sportschulen GmbH</option>
<option value="IFG Gleitschirmclub Ravensburg e.V.">IFG Gleitschirmclub Ravensburg e.V.</option>
<option value="IG Parawinch e.V.">IG Parawinch e.V.</option>
<option value="Ilmtal-Flieger e.V.">Ilmtal-Flieger e.V.</option>
<option value="Initiative Fraenkischer Gleitschirmflieger">Initiative Fraenkischer Gleitschirmflieger</option>
<option value="Jura Airlines Albatros e.V.">Jura Airlines Albatros e.V.</option>
<option value="Kleinwalsertaler Drachenflieger e.V.">Kleinwalsertaler Drachenflieger e.V.</option>
<option value="Kurpfaelzer Gleitschirmflieger Heidelberg e.V.">Kurpfaelzer Gleitschirmflieger Heidelberg e.V.</option>
<option value="Lattenberger Flugsaurier e.V.">Lattenberger Flugsaurier e.V.</option>
<option value="Leichtflieger-Oberlausitz e.V.">Leichtflieger-Oberlausitz e.V.</option>
<option value="Lenggrieser Gleitschirmflieger e.V.">Lenggrieser Gleitschirmflieger e.V.</option>
<option value="Lilienthal-Gleiter-Unterfranken e.V.">Lilienthal-Gleiter-Unterfranken e.V.</option>
<option value="Luftsportclub Bayer Leverkusen e.V.">Luftsportclub Bayer Leverkusen e.V.</option>
<option value="Luftsportgemeinschaft Bienwald-Falken e.V.">Luftsportgemeinschaft Bienwald-Falken e.V.</option>
<option value="Luftsportgemeinschaft Harz">Luftsportgemeinschaft Harz</option>
<option value="Luftsportverein Alsfeld e.V.">Luftsportverein Alsfeld e.V.</option>
<option value="Luftsportverein Crawinkel e.V.">Luftsportverein Crawinkel e.V.</option>
<option value="Luftsportverein Egge e.V.">Luftsportverein Egge e.V.</option>
<option value="Luftsportverein Neuseenland e.V.">Luftsportverein Neuseenland e.V.</option>
<option value="Luftsportverein Neustadt Glewe e.V.">Luftsportverein Neustadt Glewe e.V.</option>
<option value="Luftsportverein Parchim e.V.">Luftsportverein Parchim e.V.</option>
<option value="Luftsportverein Torgau-Beilrode e.V.">Luftsportverein Torgau-Beilrode e.V.</option>
<option value="Luftsportverein Zeitz e.V.">Luftsportverein Zeitz e.V.</option>
<option value="Luftsportvereinigung Greiling e.V.">Luftsportvereinigung Greiling e.V.</option>
<option value="Main-Taunus-Flug Dauborn e.V.">Main-Taunus-Flug Dauborn e.V.</option>
<option value="Mittag team e.V. Immenstadt">Mittag team e.V. Immenstadt</option>
<option value="Motorschirmfreunde-Pfalz e.V.">Motorschirmfreunde-Pfalz e.V.</option>
<option value="MuenstAIRland-GS-u. HG Verein">MuenstAIRland-GS-u. HG Verein</option>
<option value="Naturfreunde und Freiflieger Grosser">Naturfreunde und Freiflieger Grosser</option>
<option value="Nordbayerische Drachenflieger e.V.">Nordbayerische Drachenflieger e.V.</option>
<option value="Nordhessischer Gleitschirm-Club Kassel e.V.">Nordhessischer Gleitschirm-Club Kassel e.V.</option>
<option value="Oase-Pilotenclub">Oase-Pilotenclub</option>
<option value="Oberfraenkischer Haengegleiter Verein Coburg e.V.">Oberfraenkischer Haengegleiter Verein Coburg e.V.</option>
<option value="Oberstdorfer Drachen- und Gleitschirmflieger e.V.">Oberstdorfer Drachen- und Gleitschirmflieger e.V.</option>
<option value="OFS-Pilotenclub">OFS-Pilotenclub</option>
<option value="Oppenauer Gleitschirmflieger e.V.">Oppenauer Gleitschirmflieger e.V.</option>
<option value="Ortenauer Drachen- und Gleitschirmflieger e.V.">Ortenauer Drachen- und Gleitschirmflieger e.V.</option>
<option value="Ostallgaeuer Gleitschirmflieger e.V.">Ostallgaeuer Gleitschirmflieger e.V.</option>
<option value="Ostrachtaler Gleitschirmflieger e.V.">Ostrachtaler Gleitschirmflieger e.V.</option>
<option value="Ostthueringer Drachen- u. Gleitschirmfliegerverein e.V.">Ostthueringer Drachen- u. Gleitschirmfliegerverein e.V.</option>
<option value="Ostwindfreunde e.V.">Ostwindfreunde e.V.</option>
<option value="Para-Air Augsburg West e.V.">Para-Air Augsburg West e.V.</option>
<option value="Paraclub Kressberg">Paraclub Kressberg</option>
<option value="Parafly Franken e.V.">Parafly Franken e.V.</option>
<option value="Paragleiter- und Delta Flugsportverein Engstingen e.V.">Paragleiter- und Delta Flugsportverein Engstingen e.V.</option>
<option value="Paragliding Hof/Saale Drachen-u. Gleitschirm-Windengemeinschaft e.V.">Paragliding Hof/Saale Drachen-u. Gleitschirm-Windengemeinschaft e.V.</option>
<option value="Paragliding Nordwest e.V.">Paragliding Nordwest e.V.</option>
<option value="Paragliding-West e.V.">Paragliding-West e.V.</option>
<option value="PC Werratal-Eschwege-Eichsfeld e.V.">PC Werratal-Eschwege-Eichsfeld e.V.</option>
<option value="Pfaelzer Gleitschirm Club e.V.">Pfaelzer Gleitschirm Club e.V.</option>
<option value="Pfrontener Falken e.V.">Pfrontener Falken e.V.</option>
<option value="Rhoener Drachen- u. Gleitschirmflieger Poppenhausen e.V.">Rhoener Drachen- u. Gleitschirmflieger Poppenhausen e.V.</option>
<option value="Ruhrpott-Paragliding e.V.">Ruhrpott-Paragliding e.V.</option>
<option value="Sauerlandair e.V.">Sauerlandair e.V.</option>
<option value="Schleppgemeinschaft Bergstrasse e.V.">Schleppgemeinschaft Bergstrasse e.V.</option>
<option value="Schleppgemeinschaft Uelhof e.V.">Schleppgemeinschaft Uelhof e.V.</option>
<option value="Schleppteam Wilder Sueden">Schleppteam Wilder Sueden</option>
<option value="Schrattenbach Flieger e.V.">Schrattenbach Flieger e.V.</option>
<option value="Schwaebischer Albverein OG Schrozberg e.V.">Schwaebischer Albverein OG Schrozberg e.V.</option>
<option value="Schwangauer Drachenflieger e.V.">Schwangauer Drachenflieger e.V.</option>
<option value="Schweinfurter Gleitschirmfreunde e.V.">Schweinfurter Gleitschirmfreunde e.V.</option>
<option value="SG Stern Deutschland e.V.">SG Stern Deutschland e.V.</option>
<option value="SG Stern Rastatt">SG Stern Rastatt</option>
<option value="SG-Stern Gaggenau">SG-Stern Gaggenau</option>
<option value="SG-Stern Woerth/Germersheim in SG-">SG-Stern Woerth/Germersheim in SG-</option>
<option value="Silent Wings Gleitschirmclub e.V.">Silent Wings Gleitschirmclub e.V.</option>
<option value="Sindelfinger Drachen- u. Gleitschirmflieger e.V.">Sindelfinger Drachen- u. Gleitschirmflieger e.V.</option>
<option value="SkyTeam-Neuss e.V.">SkyTeam-Neuss e.V.</option>
<option value="Spiesshornfalken Bernau e.V.">Spiesshornfalken Bernau e.V.</option>
<option value="Suedpfaelzer Gleitschirmflieger Club e.V.">Suedpfaelzer Gleitschirmflieger Club e.V.</option>
<option value="SV Oberes Banfetal e.V.">SV Oberes Banfetal e.V.</option>
<option value="SV-Schnathorst 1925 e.V.">SV-Schnathorst 1925 e.V.</option>
<option value="Taelesflieger Deggingen e.V.">Taelesflieger Deggingen e.V.</option>
<option value="Thermik-Flieger Flying Turtles e.V.">Thermik-Flieger Flying Turtles e.V.</option>
<option value="TSV Seissen Drachenflieger e.V.">TSV Seissen Drachenflieger e.V.</option>
<option value="Turbu-Lenzen Isental e.V.">Turbu-Lenzen Isental e.V.</option>
<option value="Turnverein Bissingen e.V.">Turnverein Bissingen e.V.</option>
<option value="Ultraleicht- und Drachenfliegerclub Forst Sengenthal e.V.">Ultraleicht- und Drachenfliegerclub Forst Sengenthal e.V.</option>
<option value="Warener Luftsportverein e.V.">Warener Luftsportverein e.V.</option>
<option value="Warsteiner Skyglider Team e.V.">Warsteiner Skyglider Team e.V.</option>
<option value="Westallgaeuer Drachen- und Gleitschirmflieger e.V.">Westallgaeuer Drachen- und Gleitschirmflieger e.V.</option>
<option value="Westallgaeuer Thermikzipfel e.V.">Westallgaeuer Thermikzipfel e.V.</option>
<option value="Windenclub Eifelthermik">Windenclub Eifelthermik</option>
<option value="Windengemeinschaft Sky Rider e.V.">Windengemeinschaft Sky Rider e.V.</option>
<option value="Wippertaler Drachenflugverein e.V.">Wippertaler Drachenflugverein e.V.</option>
<option value="Wolkenkratzer e.V.">Wolkenkratzer e.V.</option>
<option value="Parateam-Pannonia e.V.">Parateam-Pannonia e.V.</option>
<option value="Sky Club Austria e.V.">Sky Club Austria e.V.</option>